#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d   󰎆 󰙯 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#AutoStart applications
dunst &
$HOME/.i3/polybar.sh
picom --config $HOME/.config/picom.conf  &
nitrogen --restore &
sxhkd
